// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi90K59qtefxigs4Az7qZxcdCbZAtpABg',
    appId: '1:523566161321:web:3dd1aaba7818e37c0c38b8',
    messagingSenderId: '523566161321',
    projectId: 'appcheckmvp',
    authDomain: 'appcheckmvp.firebaseapp.com',
    storageBucket: 'appcheckmvp.appspot.com',
    measurementId: 'G-W1YNZY7DHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJobJJeYpAoSaQFX5UH-uFxSvGCbYr6AY',
    appId: '1:523566161321:android:2f29a9438a02768c0c38b8',
    messagingSenderId: '523566161321',
    projectId: 'appcheckmvp',
    storageBucket: 'appcheckmvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5jHz4YfSgfCOgCZoXv-z6H3d-RQLabM',
    appId: '1:523566161321:ios:81b7640b32e84b780c38b8',
    messagingSenderId: '523566161321',
    projectId: 'appcheckmvp',
    storageBucket: 'appcheckmvp.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAppcheckTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz5jHz4YfSgfCOgCZoXv-z6H3d-RQLabM',
    appId: '1:523566161321:ios:e656708198852e5e0c38b8',
    messagingSenderId: '523566161321',
    projectId: 'appcheckmvp',
    storageBucket: 'appcheckmvp.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAppcheckTest.RunnerTests',
  );
}
