// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmEf2BQ1_4_L0hb2XeUiia5QVGuIiVT6M',
    appId: '1:711063819559:web:566db285fa4b7d8f464502',
    messagingSenderId: '711063819559',
    projectId: 'fir-appcheck-poc',
    authDomain: 'fir-appcheck-poc.firebaseapp.com',
    storageBucket: 'fir-appcheck-poc.appspot.com',
    measurementId: 'G-E6PW4XCH09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbW5H0jQmrD4wz5-2Srn4HCFLmwnVM1c',
    appId: '1:711063819559:android:9202011100fd91ea464502',
    messagingSenderId: '711063819559',
    projectId: 'fir-appcheck-poc',
    storageBucket: 'fir-appcheck-poc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90AA2kawRVrX8UjJ_oOTJDdBxgFQ7csc',
    appId: '1:711063819559:ios:d4c62719d325a700464502',
    messagingSenderId: '711063819559',
    projectId: 'fir-appcheck-poc',
    storageBucket: 'fir-appcheck-poc.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAppcheckTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA90AA2kawRVrX8UjJ_oOTJDdBxgFQ7csc',
    appId: '1:711063819559:ios:4d11c7e724c833f9464502',
    messagingSenderId: '711063819559',
    projectId: 'fir-appcheck-poc',
    storageBucket: 'fir-appcheck-poc.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseAppcheckTest.RunnerTests',
  );
}
